<?php

$german = array(
	"langCode"=>"de",
	"pageDoesNotExist"=>"Seite nicht gefunden.",

	"dieFreieSeekarte"=>"die freie Seekarte",

	// Menu ---------------------------------------------------------
	"Seekarte"				=>"Seekarte",
	"Vollbild"				=>"Vollbild",
	"VollbildAnzeigen"		=>"Karte im Vollbild anzeigen",
	"SeaChart"				=>"Seekarte",
	"ÜberOpenSeaMap"		=>"Über OpenSeaMap",
	"Impressum"				=>"Impressum",
	"Startseite"			=>"Startseite",
	"ÄhnlicheProjekte"		=>"Ähnliche Projekte",
	"SomeRights"			=>"Diese Seite ist unter der Lizenz Creative Commons Attribution-ShareAlike 2.0 verfügbar.",
	"descrSkipperGuide"		=>"Beschreibung auf SkipperGuide",
	"descrOpenPortGuide"	=>"Wetter auf OpenPortGuide",
	"Werkzeuge"				=>"Werkzeuge",

	// Buttons-------------------------------------------------------
	"save"			=>"Speichern",
	"ok"			=>"OK",
	"cancel"		=>"Abbrechen",
	"close"			=>"Schließen",
	"reload"		=>"Neu Laden",
	"download"		=>"Herunterladen",
	"edit"			=>"Bearbeiten",
	"move"			=>"Verschieben",
	"delete"		=>"Löschen",
	"login"			=>"Anmelden",
	"logout"		=>"Abmelden",
	"createAccount"	=>"Benutzerkonto erstellen",
	"help"			=>"Hilfe",
	"language"		=>"Sprache",
	"downloadChart"	=>"Karte Herunterladen",

	// Map-----------------------------------------------------------
	"pleaseSelect"	=>"Bitte Wählen",

	// Weather-------------------------------------------------------
	"weather"			=>"Wetter",
	"time"				=>"Zeit",
	"wind"				=>"Wind",
	"AirPressure"		=>"Luftdruck",
	"AirTemperature"	=>"Temperatur",
	"precipitation"		=>"Niederschlag",
	"WaveHeight"		=>"Wellenhöhe",
	"tide"				=>"Tide",
	"humidity"			=>"rel. Luftfeuchtigkeit",
	"clouds"			=>"Bewölkung",

	// Map View------------------------------------------------------
	"mapview"			=> "Kartenansicht",
	"depth"				=> "Wassertiefe",
	//""				=> "Häfen",
	""		=> "Taucher",
	""		=> "Sportlayer (Regatta)",
	""		=> "Kajakfahrer",
	""		=> "Binnenschiffer",
	""		=> "AIS",

	// Editor--------------------------------------------------------
	"editSeamark"=>"Seezeichen Bearbeiten",
	"editHarbour"=>"Hafen Bearbeiten",
	"add"=>"Hinzufügen",
	"data"=>"Daten",
	"unknown"=>"Unbekannt",
	"comment"=>"Kommentar",
	"note"=>"Bemerkungen",
	"logged_in"=>"Willkommen",
	"logged_out"=>"Sie müssen angemeldet sein um die Karte bearbeiten zu können.",
	"logged_out_save"=>"Sie müssen angemeldet sein um die Daten zu speichern.",
	"enterComment"=>"Sie müssen einen Kommentar eingeben!",
	"positionSeamark"=>"Position des Seezeichens",
	"userName"=>"Benutzername",
	"password"=>"Passwort",
	"dataLoad"=>"Daten werden geladen.",
	"loading"=>"Laden",
	"dataSave"=>"Daten werden gespeichert.",
	"changesetCreate"=>"Changeset wird erzeugt.",
	"changesetClose"=>"Changeset wird geschlossen.",
	"seamarkAdd"=>"Seezeichen hinzufügen",
	"seamarkEdit"=>"Seezeichen bearbeiten",
	"seamarkDelete"=>"Seezeichen löschen",
	"seamarkMove"=>"Seezeichen verschieben",
	"seamarkSave"=>"Seezeichen speichern",
	"seamarkCategory"=>"Art des Zeichens",
	"seamarkType"=>"Bauart des Zeichens",
	"seamarkName"=>"Name des Zeichens",
	"harbourCategory"=>"Art des Hafens",
	"harbourName"=>"Name des Hafens",
	"comboUnknown"=>"Unbekannt- - - - - - - - - - - - -",
	"comboSafeWater"=>"Ansteuerung",
	"comboPort"=>"Backbord",
	"comboStarboard"=>"Steuerbord",
	"comboPrefPort"=>"Abzweigung Backbord",
	"comboPrefStarboard"=>"Abzweigung Steuerbord",
	"comboNorth"=>"Gefahr Nord",
	"comboEast"=>"Gefahr Ost",
	"comboSouth"=>"Gefahr Süd",
	"comboWest"=>"Gefahr West",
	"comboIsolatedDanger"=>"Einzelgefahrenzeichen",
	"comboSpecialPurpose"=>"Sonderzeichen",
	"sphere"=>"Kugeltonne",
	"conical"=>"Spitztonne",
	"can"=>"Stumpftonne",
	"barrel"=>"Fasstonne",
	"pillar"=>"Bakentonne",
	"spar"=>"Spierentonne",
	"beacon"=>"Bake",
	"stake"=>"Spiere",
	"perch"=>"Pricke",
	"topmark"=>"Topzeichen",
	"radar"=>"Radarreflektor",
	"lighted"=>"Befeuert",
	"fogsignal"=>"Nebelhorn",
	"miscItems"=>"Weitere<br/>Eigenschaften",
	"colour"=>"Farbe",
	"red"=>"Rot",
	"yellow"=>"Gelb",
	"red_white"=>"Rot;Weiß;Rot",
	"character"=>"Kennung",
	"period"=>"Wiederkehr",
	"haveAccount"=>"Sie haben noch kein<br/>OSM Benutzerkonto?",
	"zoomToSmall"=>"Die Zoomstufe ist zu klein.<br/>Bitte zoome weiter in die Karte. <br/>Ein Bearbeiten ist ab Stufe 16 möglich.  <br/> Aktueller Zoom: ",
	"noData"=>"Es konnten keine Daten <br/>geladen werden!",
	"online_editor"=>"OpenSeaMap - Editor",
	"about_editor"=>"Über Online - Editor",
	"version"=>"Version",
	"author"=>"Autor",
	"license"=>"Lizenz",
	"historyNode"=>"Geschichte des Elements",
	"reportBugs"=>"Bitte verwenden Sie den <a href='http://sourceforge.net/tracker/?func=browse&group_id=273418&atid=1162128' target='blank'>SourceForge Tracker</a><br/>für Problemberichte.",


	//Network -------------------------------------------------------
	"send401"=>"Anmeldung Fehlgeschlagen: Benutzername oder Passwort falsch!",
	"send404"=>"Speichern Fehlgeschlagen: Der OSM-Datenbankserver antwortet nicht!",

	// Urls ---------------------------------------------------------
	"UrlOSM"=>"http://openstreetmap.de",
	"UrlOSMWiki_Hauptseite"=>"http://wiki.openstreetmap.org/wiki/Hauptseite",
	"UrlOSMWiki_OpenSeaMap"=>"http://wiki.openstreetmap.org/wiki/DE:OpenSeaMap",
	"UrlGPLV3"=>"http://www.gnu.de/documents/gpl.de.html",
	"UrlEditor"=>"./map/map_edit.php?lang=de",

	// Legende ------------------------------------------------------
	"Legende"=>"Legende",
	"Seezeichen"=>"Seezeichen",
	"Leuchtfeuer"=>"Leuchtfeuer",
	"BrückenSchleusen"=>"Brücken/Schleusen",
	//Harbour
	"harbour"=>"Hafen",
	"harbours"=>"Häfen",
	"marina"=>"Marina",
	"breakwater"=>"Wellenbrecher",
	"pier"=>"Steg, Schwimmsteg, Seebrücke",
	"crane"=>"Kran",
	"slipway"=>"Bootsrampe, Slipanlage",
	"harbour_master"=>"Hafenmeister",
	"waste_disposal"=>"Fäkalienentsorgung",
	//Seamarks
	"safe_water"=>"Sicheres Fahrwasser, Ansteuerung",
	"lateral_port"=>"Fahrwassertonne Backbord",
	"lateral_starboard"=>"Fahrwassertonne Steuerbord",
	"lateral_pref_port"=>"Durchgehendes Fahrwasser: Backbord",
	"lateral_pref_starboard"=>"Durchgehendes Fahrwasser: Steuerbord",
	"cardinal_north"=>"Seezeichen nördlich der Gefahrenstelle",
	"cardinal_east"=>"Seezeichen östlich der Gefahrenstelle",
	"cardinal_south"=>"Seezeichen südlich der Gefahrenstelle",
	"cardinal_west"=>"Seezeichen westlich der Gefahrenstelle",
	"isolated_danger"=>"Einzelgefahrenzeichen",
	"special_purpose"=>"Kennzeichnung besonderer Gebiete",
	//Lights
	"lighthouse"=>"Leuchtturm",
	"beacon_green"=>"Molenfeuer grünes Licht",
	"beacon_red"=>"Molenfeuer rotes Licht",
	"beacon_white"=>"Molenfeuer weißes Licht",
	//Locks
	"lock_gate"=>"Schleusentor",
	"lock"=>"Schleuse",
	"wier_small"=>"Wehr (klein)",
	"wier_big"=>"Wehr (groß)",

	// Online-Help --------------------------------------------------
	"helpPositionDialog"=>"Bitte klicke auf die Karte,<br/>oder gebe die Koordinaten von Hand ein,<br/>um eine neue Position festzulegen.",
	"helpSeamarkSaved"=>"Das Seezeichen wurde gespeichert.<br/>Es kann bis zu 2 Tage dauern bevor es<br/>auf der Karte sichtbar ist.",

	// Error-Messages -----------------------------------------------
	"xmlLoadError"=>"Fehler: Das Laden der OSM-XML-Datei ist fehlgeschlagen.Bitte wählen Sie einen größeren Zoomlevel, oder versuchen es später noch einmal.",
);

?>
