<?php

$espanol = array(
	"langCode"=>"es",
	"pageDoesNotExist"=>"Página no encontrada.",

	"dieFreieSeekarte"=>"La Carta Náutica libre",

	// Menu ---------------------------------------------------------
	"Seekarte"			=>"Carta Náutica",
	"Vollbild"			=>"Pantalla completa",
	"VollbildAnzeigen"	=>"Mostrar pantalla ocmpleta",
	"SeaChart"			=>"Carta Náutica (pantalla completa)",
	"ÜberOpenSeaMap"	=>"Acerca de OpenSeaMap",
	"Impressum"			=>"Apartado legal",
	"Startseite"		=>"Página de inicio",
	"ÄhnlicheProjekte"	=>"Proyectos similares",
	"SomeRights"		=>"Este trabajo está bajo la licencia Creative Commons Attribution-ShareAlike 2.0",

	// Buttons-------------------------------------------------------
	"save"			=>"Grabar",
	"ok"			=>"OK",
	"cancel"		=>"Cancelar",
	"close"			=>"Cerrar",
	"reload"		=>"Recargar",
	"edit"			=>"Editar",
	"move"			=>"Mover",
	"delete"		=>"Eliminar",
	"login"			=>"Entrar",
	"logout"		=>"Salir",
	"createAccount"	=>"Crear nueva cuenta",
	"help"			=>"Ayuda",
	"language"		=>"Idioma",

	// Editor--------------------------------------------------------
	"add"=>"Añadir",
	"data"=>"Datos",
	"unknown"=>"Desconocido",
	"comment"=>"Comentario",
	"logged_in"=>"Welcome",
	"logged_out"=>"You must be logged in to edit the chart.",
	"logged_out_save"=>"You must be logged in to save the data.",
	"enterComment"=>"¡Por favor introduzca un comentario!",
	"positionSeamark"=>"Position of sea mark",
	"userName"=>"Usuario",
	"password"=>"Contraseña",
	"dataLoad"=>"Cargando datos.",
	"dataSave"=>"Grabando datos.",
	"changesetCreate"=>"Creando conjunto de cambios.",
	"changesetClose"=>"Cerrando conjunto de cambios.",
	"seamarkAdd"=>"Añadir baliza",
	"seamarkEdit"=>"Editar baliza",
	"seamarkDelete"=>"Eliminar baliza",
	"seamarkMove"=>"Mover baliza",
	"seamarkSave"=>"Grabar baliza",
	"seamarkCategory"=>"Categoría de balizas",
	"seamarkType"=>"Capa de balizas",
	"seamarkName"=>"Nombre de la baliza",
	"comboUnknown"=>"Desconocido- - - - - - - - - - - - -",
	"comboSafeWater"=>"Aguas seguras",
	"comboPort"=>"Babor",
	"comboStarboard"=>"Estribor",
	"comboPrefPort"=>"Preferido: babor",
	"comboPrefStarboard"=>"Preferido: estribor",
	"comboNorth"=>"Cardinal norte",
	"comboEast"=>"Cardinal este",
	"comboSouth"=>"Cardinal sur",
	"comboWest"=>"Cardinal oeste",
	"comboIsolatedDanger"=>"Peligro aislado",
	"comboSpecialPurpose"=>"Proposito especial",
	"sphere"=>"Esférica",
	"conical"=>"Cónica",
	"can"=>"Bidón",
	"barrel"=>"Tonel",
	"pillar"=>"Pilar",
	"spar"=>"Palo",
	"beacon"=>"Baliza",
	"topmark"=>"Marca de tope",
	"radar"=>"Reflector rádar",
	"lighted"=>"Fanal",
	"fogsignal"=>"Señal de niebla",
	"miscItems"=>"More <br>properties",
	"colour"=>"Color",
	"red"=>"rojo",
	"yellow"=>"amarillo",
	"character"=>"Carácter",
	"period"=>"Period",
	"haveAccount"=>"¿No tienes una cuenta<br/>de OSM aún? ",

	//Network -------------------------------------------------------
	"send401"=>"Validación fallida: ¡Nombre de usuario o contraseña incorrecta!",
	"send404"=>"Grabación fallida: ¡El servidor de la base de datos de OSM no responde!",
	
	// Urls ---------------------------------------------------------
	"UrlOSM"=>"http://openstreetmap.org",
	"UrlOSMWiki_Hauptseite"=>"http://wiki.openstreetmap.org/wiki/ES:Main_Page",
	"UrlOSMWiki_OpenSeaMap"=>"http://wiki.openstreetmap.org/wiki/OpenSeaMap",

	// Legende ------------------------------------------------------
	"Legende"=>"Leyenda",
	"Hafen"=>"Puerto",
	"Seezeichen"=>"Balizas",
	"Leuchtfeuer"=>"Luces",
	"BrückenSchleusen"=>"Puentes/Esclusas",
	//Harbour
	"breakwater"=>"Breakwater",
	"pier"=>"Pier",
	"crane"=>"Crane",
	"slipway"=>"Slipway",
	"harbour_master"=>"Harbour Master",
	"waste_disposal"=>"Waste Disposal",
	//Seamarks
	"safe_water"=>"Safe water",
	"lateral_port"=>"Port mark",
	"lateral_starboard"=>"Starboard mark",
	"lateral_pref_port"=>"Preferred channel: port",
	"lateral_pref_starboard"=>"Preferred channel: starboard",
	"cardinal_north"=>"North cardinal mark",
	"cardinal_east"=>"East cardinal mark",
	"cardinal_south"=>"South cardinal mark",
	"cardinal_west"=>"West cardinal mark",
	"isolated_danger"=>"Isolated danger mark",
	"special_purpose"=>"Special mark",
	//Lights
	"lighthouse"=>"Lighthouse",
	"beacon_green"=>"Green beacon",
	"beacon_red"=>"Red beacon",
	"beacon_white"=>"White beacon",
	//Locks
	"lock_gate"=>"Lock gate",
	"lock"=>"Lock",
	"wier_small"=>"Wier (small)",
	"wier_big"=>"Wier (big)",
);

?>