<?php

$english = array(
	"langCode"=>"en",
	"pageDoesNotExist"=>"Page not found.",

	"dieFreieSeekarte"=>"The free nautical chart",

	// Menu ---------------------------------------------------------
	"Seekarte"			=>"Nautical Chart",
	"Vollbild"			=>"Fullscreen",
	"VollbildAnzeigen"	=>"Show Fullscreen",
	"SeaChart"			=>"Nautical Chart",
	"ÜberOpenSeaMap"	=>"About OpenSeaMap",
	"Impressum"			=>"Legal",
	"Startseite"		=>"Main Page",
	"ÄhnlicheProjekte"	=>"Similar Projects",
	"SomeRights"		=>"This work is licensed under the Creative Commons Attribution-ShareAlike 2.0 License",
	"descrSkipperGuide"	=>"Description on SkipperGuide (German)",

	// Buttons-------------------------------------------------------
	"save"			=>"Save",
	"ok"			=>"OK",
	"cancel"		=>"Cancel",
	"close"			=>"Close",
	"reload"		=>"Reload",
	"edit"			=>"Edit",
	"move"			=>"Move",
	"delete"		=>"Delete",
	"login"			=>"Login",
	"logout"		=>"Logout",
	"createAccount"	=>"Create New Account",
	"help"			=>"Help",
	"language"		=>"Language",

	// Editor--------------------------------------------------------
	"editSeamark"=>"Edit sea marks",
	"add"=>"Add",
	"data"=>"Data",
	"unknown"=>"Unknown",
	"comment"=>"Comment",
	"note"=>"Notes",
	"logged_in"=>"Welcome",
	"logged_out"=>"You must be logged in to edit the chart.",
	"logged_out_save"=>"You must be logged in to save the data.",
	"enterComment"=>"Please enter a comment!",
	"positionSeamark"=>"Position of sea mark",
	"userName"=>"Username",
	"password"=>"Password",
	"dataLoad"=>"Loading Data.",
	"loading"=>"Loading",
	"dataSave"=>"Saving Data.",
	"changesetCreate"=>"Creating Changeset.",
	"changesetClose"=>"Closing Changeset.",
	"seamarkAdd"=>"Add sea mark",
	"seamarkEdit"=>"Edit sea mark",
	"seamarkDelete"=>"Delete sea mark",
	"seamarkMove"=>"Move sea mark",
	"seamarkSave"=>"Save sea mark",
	"seamarkCategory"=>"Sea mark category",
	"seamarkType"=>"Sea mark shape",
	"seamarkName"=>"Sea mark name",
	"comboUnknown"=>"Unknown- - - - - - - - - - - - -",
	"comboSafeWater"=>"Safe water",
	"comboPort"=>"Port",
	"comboStarboard"=>"Starboard",
	"comboPrefPort"=>"Preferred: port",
	"comboPrefStarboard"=>"Preferred: starboard",
	"comboNorth"=>"Cardinal north",
	"comboEast"=>"Cardinal east",
	"comboSouth"=>"Cardinal south",
	"comboWest"=>"Cardinal west",
	"comboIsolatedDanger"=>"Isolated danger",
	"comboSpecialPurpose"=>"Special purpose",
	"sphere"=>"Sphere",
	"conical"=>"Conical",
	"can"=>"Can",
	"barrel"=>"Barrel",
	"pillar"=>"Pillar",
	"spar"=>"Spar",
	"beacon"=>"Beacon",
	"topmark"=>"Topmark",
	"radar"=>"Radar reflector",
	"lighted"=>"Lighted",
	"fogsignal"=>"Fogsignal",
	"miscItems"=>"More <br>properties",
	"colour"=>"Colour",
	"red"=>"red",
	"yellow"=>"yellow",
	"red_white"=>"Red;Withe;Red",
	"character"=>"Character",
	"period"=>"Period",
	"haveAccount"=>"Don't have an OSM<br/>Account yet?",
	"zoomToSmall"=>"The zoom level is to small.<br/>Please zoom in.<br/>Editing will be possible on Level 16.<br/>Current Zoom: ",
	"noData"=>"Failed to load data!",
	"online_editor"=>"OpenSeaMap - Editor",
	"about_editor"=>"About Online - Editor",
	"version"=>"Version",
	"author"=>"Author",
	"license"=>"License",
	"historyNode"=>"History of the element",
	"reportBugs"=>"Please use the <a href='http://sourceforge.net/tracker/?func=browse&group_id=273418&atid=1162128' target='blank'>SourceForge Tracker</a><br/>for bug reports.",

	//Network -------------------------------------------------------
	"send401"=>"Login failed: Incorrect username or password!",
	"send404"=>"Saving failed: The OSM-Database server doesn't respond!",
	
	// Urls ---------------------------------------------------------
	"UrlOSM"=>"http://openstreetmap.org",
	"UrlOSMWiki_Hauptseite"=>"http://wiki.openstreetmap.org/wiki/Main_Page",
	"UrlOSMWiki_OpenSeaMap"=>"http://wiki.openstreetmap.org/wiki/OpenSeaMap",
	"UrlGPLV3"=>"http://www.gnu.de/documents/gpl-3.0.en.html",
	"UrlEditor"=>"./map/map_edit.php?lang=en",

	// Legende ------------------------------------------------------
	"Legende"=>"Map Key",
	"Hafen"=>"Harbour",
	"Seezeichen"=>"Sea Marks",
	"Leuchtfeuer"=>"Lights",
	"BrückenSchleusen"=>"Bridges/Locks",
	//Harbour
	"harbour"=>"Harbour",
	"harbours"=>"Harbours",
	"marina"=>"Marina",
	"breakwater"=>"Breakwater",
	"pier"=>"Pier",
	"crane"=>"Crane",
	"slipway"=>"Slipway",
	"harbour_master"=>"Harbour Master",
	"waste_disposal"=>"Waste Disposal",
	//Seamarks
	"safe_water"=>"Safe water",
	"lateral_port"=>"Port mark",
	"lateral_starboard"=>"Starboard mark",
	"lateral_pref_port"=>"Preferred channel: port",
	"lateral_pref_starboard"=>"Preferred channel: starboard",
	"cardinal_north"=>"North cardinal mark",
	"cardinal_east"=>"East cardinal mark",
	"cardinal_south"=>"South cardinal mark",
	"cardinal_west"=>"West cardinal mark",
	"isolated_danger"=>"Isolated danger mark",
	"special_purpose"=>"Special mark",
	//Lights
	"lighthouse"=>"Lighthouse",
	"beacon_green"=>"Green beacon",
	"beacon_red"=>"Red beacon",
	"beacon_white"=>"White beacon",
	//Locks
	"lock_gate"=>"Lock gate",
	"lock"=>"Lock",
	"wier_small"=>"Wier (small)",
	"wier_big"=>"Wier (big)",

	// Online-Help --------------------------------------------------
	"helpPositionDialog"=>"Please click on the map,<br/>or enter the coordinates manually,<br/>to set a new position.",
	"helpSeamarkSaved"=>"The sea mark has been saved.<br/>It can take up to two days<br/>before it is visible on the map.",

	// Error-Messages -----------------------------------------------
	"xmlLoadError"=>"Error: Loading the OSM-XML-Data failed. Please select a higher zoomlevel, or try again later on.",
);

?>