<h2>Häufig gestellte Fragen</h2>
<p>
	<strong>Was ist OpenSeaMap?</strong><br>OpenSeaMap ist ein weltweites Opensource-Projekt zur Erstellung einer freien Seekarte. Es besteht ein großer Bedarf an frei zugänglichen Karten für die Seefahrt. Deshalb wurde 2009 das Projekt ins Leben gerufen. Das Ziel von OpenSeaMap ist es, für den Seemann interessante nautische und touristische Information in die freie Weltkarte einzutragen und in nautisch ansprechender Weise darzustellen. Dazu gehören Leuchtfeuer, Tonnen und andere Seezeichen, Hafen-Informationen, Reparaturwerkstätten, Schiffszubehör und vieles mehr, aber auch Einkaufsmöglichkeiten, Restaurants und Sehenswürdigkeiten. OpenSeamap ist ein Teil-Projekt von <a href="http://www.openstreetmap.de/index.html" target="blank">OpenStreetMap</a> und verwendet dessen Datenbank.
</p>
<p>
	<strong>Wo finde ich weitere Informationen?</strong><br>Im <a href="http://wiki.openstreetmap.org/index.php/Hauptseite" target="blank">Wiki</a> gibt es zum Thema "Seekarte" folgende Seiten:
	<ul>
		<li><a href="http://wiki.openstreetmap.org/wiki/de:Seekarte" target="blank">Seekarte</a></li>
		<li><a href="http://wiki.openstreetmap.org/wiki/de:Segler" target="blank">Segler</a></li>
		<li><a href="http://wiki.openstreetmap.org/wiki/de:Hafen" target="blank">Hafen</a></li>
		<li><a href="http://wiki.openstreetmap.org/wiki/de:Leuchtfeuer" target="blank">Leuchtfeuer</a></li>
		<li><a href="http://wiki.openstreetmap.org/wiki/de:Tonne" target="blank">Tonne</a></li>
		<li><a href="http://wiki.openstreetmap.org/wiki/de:Bake" target="blank">Bake</a></li>
	</ul>
	Auf jeder Wiki-Seite gibt es viele weiterführende und vertiefende Links. Manche Links führen direkt zu Wikipedia-Artikeln, über die viele tausend Seiten Information zu allen Themen der Seefahrt und der Kartografie zu finden sind, genauso wie zu den in der Seekarte dargestellten Ländern und Orten und deren Geschichte.
</p>
<p>
	<strong>Wann wird es eine flächendeckende Seekarte geben?</strong><br>Eine wirklich fertige Seekarte wird es wahrscheinlich nie geben, da es bestimmt immer neue Sachen zu entdecken und in die Karte einzutragen gibt. Wir wollen das Rendern der Seekarte im Laufe der nächsten zwei Monate auf die gesamte Ostsee ausdehnen. Wir hoffen einen Monat später auch die Nordsee rendern zu können. In einem ähnlichen Intervall sollen die restlichen Ozeane folgen. <br>Natürlich ist es auch dann noch keine flächendeckende Seekarte. Für eine Seekarte benötigen wir Seezeichen, die wir darstellen können. Diese werden von den Community-Mitgliedern sammeln und in die OpenStreetMap-Datenbank eintragen. Du bist herzlich eingeladen mitzumachen! Wir freuen uns über jede Hilfe beim Erstellen der freien Seekarte.
</p>
<p>
	<strong>Wie kann ich mitmachen?</strong><br>
	<ul>
		<li>Du bist <b>Seemann</b>, <b>Segler</b>, <b>Motorbootfahrer</b>, <b>Kajakfahrer</b>? <br /><a href="http://wiki.openstreetmap.org/wiki/de:Segler"target="blank">Du kannst mit Deinem GPS-Gerät ganz viel für OpenSeaMap tun</a>: Wenn Du auf Törn bist, oder in der Nähe eines Hafens wohnst, geh bitte in jedem Hafen mit dem GPS einmal genau die Kante der Hafenmole und der Stege ab. Den Track lädst Du dann hoch, und wenn Du Zeit hast erstellst du daraus einen <a href="http://wiki.openstreetmap.org/wiki/de:Hafen" target="blank">Hafenplan</a>. Natürlich kannst Du alle irgendwie interessanten Informationen angeben, die dann weltweit allen Sportbootfahrern und Seeleuten zur Verfügung stehen. Du kannst auch schon zuhause beginnen und von Deinem Zielort Luftbilder abzeichnen, und die Daten dann vor Ort vervollständigen. Auch Hilfe im "kleinen Stil" ist für das Projekt sehr wertvoll: Sind die Gegenden, in denen Du Dich auskennst, korrekt erfasst, oder findest Du Fehler, die Du verbessern könntest? Arbeitest Du vielleicht sogar auf einem Schiff und kennst jede Menge Häfen in aller Welt? </li>
		<li>Du <b>zeichnest gern Luftbilder ab</b>? <br />In vielen Teilen der Welt stehen hochauflösende Luftbilder von Jahoo zur Verfügung. Daraus kannst Du genaue <a href="http://wiki.openstreetmap.org/wiki/de:Hafen" target="blank">Hafenpläne</a> erstellen und die Küstenlinie verfeinern. So kannst Du auch von schönen Reisen träumen wenn Du gerade noch zuhause bist...</li>
		<li>Du bist <b>Programmierer</b>? <br />Es gibt jede Menge zu tun – an den <a href="http://wiki.openstreetmap.org/wiki/de:Seamap-Editor"target="blank">Editoren</a>, am Renderer der die Karten zeichnet, an der Website, an der Internationalisierung, an der Datenbank, und an allen möglichen Hilfsprogrammen. Aktuell haben wir auch zwei Plätze für Diplomanden anzubieten. <br />Wir erzählen Dir gerne mehr: <a href="mailto:ohannemann@opensource-werkstatt-stubben.org?cc=liste12A45q7@gmx.de&amp;subject=Programmierer%20f&uuml;r%20OpenSeaMap">Olaf</a> </li>
		<li>Du <b>sprichst Englisch, Französisch</b>? <br />Wir möchten gern die Seekarte in möglichst vielen Sprachen anbieten. Dazu möchten wir die Website und die Anleitungen im Wiki möglichst schnell in Englisch übersetzen. Daraus können dann andere in ihre Landessprache übersetzen. <br />Wir erzählen Dir gerne mehr: <a href="mailto:tristan.thomas@wikinewsie.org">Tristan</a> </li>
		<li>Du bist <b>Grafiker</b>? <br />Ein Bild sagt mehr als tausend Worte. Du könntest unser Wiki illustrieren, Icons für die Karte zeichnen, Grafiken und Layout optimieren, Bilddateien organisieren und verwalten. <br />Wir erzählen Dir gerne mehr: <a href="mailto:liste12A45q7@gmx.de?cc=ohannemann@opensource-werkstatt-stubben.org&amp;subject=Grafiker%20f&uuml;r%20OpenSeaMap">Markus</a> </li>
		<li>Du bist <b>Hafenkapitän, Marinabetreiber, Reeder, Vercharterer</b>? Du hast vielleicht Zugriff auf Daten, die OpenSeaMap verwenden könnte? Luftbilder, Karten und Hafenpläne, Listen, Tabellen, Verzeichnisse? Immer her damit, das können wir sicher irgendwo gut gebrauchen. <br />Wir erzählen Dir gerne mehr: <a href="mailto:liste12A45q7@gmx.de?cc=ohannemann@opensource-werkstatt-stubben.org&amp;subject=Daten%20f&uuml;r%20OpenSeaMap">Markus</a> </li>
		<li>Du bist <b>Ozeanograf, Kartograf, Bathymeter, Meteorologe</b>? <br />Dann hast Du hast Du sicher viele Ideen, was man mit OpenSeaMap noch so alles machen könnte?! Beispielsweise suchen wir eine Lösung zur Darstellung der <a href="http://wiki.openstreetmap.org/wiki/de:Water_Depth"target="blank">Wassertiefen</a>, arbeiten an einem <a href="http://wiki.openstreetmap.org/wiki/de:Meeresprofil"target="blank">Meeresprofil</a> und experimentieren mit <a href="http://wiki.openstreetmap.org/wiki/de:AIS"target="blank">AIS</a>. Deine Hilfe können wir gut gebrauchen. <br />Wir erzählen Dir gerne mehr: <a href="mailto:liste12A45q7@gmx.de?cc=ohannemann@opensource-werkstatt-stubben.org&amp;subject=Daten%20f&uuml;r%20OpenSeaMap">Markus</a> </li>					</ul>
</p>
<p>
	<strong>Wie kann ich Seezeichen eintragen?</strong><br>Dies ist zur Zeit leider noch etwas schwierig. Der <a href="../map/map_edit.html" target="blank">Online-Editor</a> ist leider erst in einer 2. Alpha-Version online und kann noch keine Seezeichen speichern. Wir hoffen in zwei Wochen das Hinzufügen von Seezeichen fertiggestellt zu haben. In weiteren zwei Wochen sollte das Bearbeiten der Zeichen möglich sein.
</p>
<p>
	<strong>Unter welcher Lizenz steht OpenSeaMap?</strong><br>Alle Daten in der OpenStreetMap-Datenbank, also auch die von OpenSeaMap, stehen unter der Lizenz "Creative Commons Attribution-Share Alike 2.0" (auf Deutsch: <a href="http://creativecommons.org/licenses/by-sa/2.0/de/" target="blank">"Namensnennung unter gleichen Bedingungen"</a>). Die Lizenz besagt, dass jegliche Art der Nutzung von OSM-Daten, auch gewerblich, zulässig ist, es muss jedoch angegeben werden, dass die Daten von OSM stammen, und jedes Werk, das aus OSM-Daten abgeleitet wird, muss wiederum unter der CC-BY-SA-Lizenz stehen.
</p>

				<p>
					<strong>Was ist eigentlich OpenStreetMap?</strong><br><a href="http://www.openstreetmap.de/index.html" target="blank">OpenStreetMap</a> ist ein Opensource-Projekt mit dem Ziel, eine freie Weltkarte zu erschaffen. Derzeit arbeiten über 120.000 Freiwillige an diesem Projekt. Einige davon auch hier an OpenSeaMap. Genauso wie wir hier nautische Informationen sammeln, werden dort weltweit Daten über Strassen, Eisenbahnen, Flüsse, Wälder, Häuser und alles andere gesammelt, was gemeinhin auf Karten zu sehen ist. Wir benutzen für OpenSeaMap die gleichen Daten wie OpenStreetMap und speichern unsere Daten in die Datenbank von OpenStreetMap. Weil wir die Daten selbst erheben und nicht aus existierenden Karten abmalen, haben wir selbst auch alle Rechte daran. Die OpenStreetMap-Daten darf jeder lizenzkostenfrei einsetzen und beliebig weiterverarbeiten. Weitere Informationen zu OpenStreetMap findet Du in den <a href="http://www.openstreetmap.de/faq.html" target="blank">OpenStreetMap-FAQs</a>.
				</p>

